-- MySQL Script generated by MySQL Workbench
-- Sat Sep  7 17:30:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vrintex
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vrintex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vrintex` DEFAULT CHARACTER SET utf8 ;
USE `vrintex` ;

-- -----------------------------------------------------
-- Table `vrintex`.`colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrintex`.`colors` (
  `id_color` INT NOT NULL AUTO_INCREMENT,
  `color_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_color`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vrintex`.`type_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrintex`.`type_product` (
  `id_type_product` INT NOT NULL AUTO_INCREMENT,
  `type_product_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_type_product`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vrintex`.`models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrintex`.`models` (
  `id_model` INT NOT NULL AUTO_INCREMENT,
  `name_model` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `id_type_product` INT NOT NULL,
  `units` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_model`),
  INDEX `typeProductId_idx` (`id_type_product` ASC) VISIBLE,
  CONSTRAINT `typeProductId`
    FOREIGN KEY (`id_type_product`)
    REFERENCES `vrintex`.`type_product` (`id_type_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vrintex`.`providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrintex`.`providers` (
  `id_provider` INT NOT NULL AUTO_INCREMENT,
  `website` VARCHAR(255) NULL,
  `tel` VARCHAR(15) NULL,
  `email` VARCHAR(100) NULL,
  `company_name` VARCHAR(100) NULL,
  PRIMARY KEY (`id_provider`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vrintex`.`list_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrintex`.`list_products` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `stock` INT NULL,
  `id_color` INT NULL,
  `id_provider` INT NULL,
  `price` FLOAT NULL,
  `id_model` INT NULL,
  PRIMARY KEY (`id_product`),
  INDEX `idColor_idx` (`id_color` ASC) VISIBLE,
  INDEX `idProvider_idx` (`id_provider` ASC) VISIBLE,
  INDEX `idModel_idx` (`id_model` ASC) VISIBLE,
  CONSTRAINT `idColor`
    FOREIGN KEY (`id_color`)
    REFERENCES `vrintex`.`colors` (`id_color`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProvider`
    FOREIGN KEY (`id_provider`)
    REFERENCES `vrintex`.`providers` (`id_provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idModel`
    FOREIGN KEY (`id_model`)
    REFERENCES `vrintex`.`models` (`id_model`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
